---
- name: AWX example playbook
  hosts: localhosts
  gather_facts: false

  tasks:
    - name: Create temp dir
      file:
        path: /tmp/mastery
        state: directory

    - name: create a file with example text
      lineinfile:
        path: /tmp/mastery/mastery.txt
        line: 'Created with Ansible Mastery!'
        create: yes
